### PR TITLE
Fix main function does not use the updated TwampSessionConfig

### LINKED ISSUE #15: main function does not use the updated TwampSessionConfig
After https://github.com/tcaine/twamp/pull/14 went in, main.go is not using the new TwampSessionConfig struct fields and for me the code is broken. I am new to this repo so please correct me if I am missing something. 

Code in question: 

```
session, err := connection.CreateSession(
		twamp.TwampSessionConfig{
			Port:    *port,
			Timeout: *wait,
			Padding: *size,
			TOS:     *tos,
		},
	)
```

### PR DESCRIPTION
**Pull request by kuhuAvtx**
Fixes #15 , @tcaine please take a look.

### CODE REVIEW

File: twamp/main.go [hunk 1]
```diff
@@ -55,7 +57,7 @@ func main() {
 
 	switch *mode {
 	case "json":
-		results := test.RunX(*count)
+		results := test.RunX(*count, nil)
```
Comment (kuhuAvtx) [inline twamp/main.go:60]: I am not sure what needs to happen here so keeping the PR in draft mode while I figure it out.

Comment (tcaine) [reply twamp/main.go:60]: You can pass in an optional callback function here.  Passing in nil should be fine.

**Review by tcaine — APPROVED** [review]

**Comment by kuhuAvtx** [comment]
Thank you @tcaine for the approval. I have moved it out of draft mode.
